name: linux

on:
  pull_request:
    branches:
      - development

jobs:
# enable again when we open-source (free core-hours for GH Actions)
#
#  linux_gcc_cxx17_ompi:
#    name: GNU@7.5 C++17 OMPI
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v2
#    - name: Dependencies
#      run: .github/workflows/setup/ubuntu_ompi.sh
#    - name: Build & Install
#      run: |
#        mkdir build
#        cd build
#        cmake ..                                   \
#            -DCMAKE_INSTALL_PREFIX=/tmp/my-hipace
#        make -j 2 VERBOSE=ON
#        ctest --output-on-failure
#        make install

  linux_gcc_cxx17_omp_ompi:
    name: GNU@7.5 C++17 OMP OMPI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Dependencies
      run: .github/workflows/setup/ubuntu_ompi.sh
    - name: Build & Install
      run: |
        mkdir build
        cd build
        cmake ..                                   \
            -DHiPACE_COMPUTE=OMP                   \
            -DCMAKE_INSTALL_PREFIX=/tmp/my-hipace  \
            -DCMAKE_CXX_STANDARD=17
        make -j 2 VERBOSE=ON
        export OMP_NUM_THREADS=2
        ctest --output-on-failure

#  linux_gcc_cxx17:
#    name: GNU@7.5 C++17 Serial
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v2
#    - name: Dependencies
#      run: .github/workflows/setup/ubuntu.sh
#    - name: Build & Install
#      run: |
#        mkdir build
#        cd build
#        cmake .. -DHiPACE_MPI=OFF
#        make -j 2 VERBOSE=ON
#        ctest --output-on-failure

# enable again when we open-source (free core-hours for GH Actions)
#
#  linux_clang7:
#    name: Clang@7 C++17 OMPI
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v2
#    - name: Dependencies
#      run: .github/workflows/setup/ubuntu_clang.sh
#    - name: Build & Install
#      run: |
#        mkdir build
#        cd build
#        cmake ..                                           \
#            -DCMAKE_C_COMPILER=$(which clang-7)            \
#            -DCMAKE_CXX_COMPILER=$(which clang++-7)
#        make -j 2 VERBOSE=ON
#        ctest --output-on-failure
