name: macos

on: [push, pull_request]

jobs:
  macos_appleclang_cxx14_ompi:
    name: AppleClang@11.0 C++14 OMPI
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Dependencies
      run: .github/workflows/setup/macos.sh
    - name: Build & Install
      run: |
        mkdir build
        cd build
        cmake ..                                   \
            -DCMAKE_INSTALL_PREFIX=/tmp/my-hipace
        make -j 2 VERBOSE=ON
        ctest --output-on-failure
        make install
