name: 🍏 macOS

on: [push, pull_request]

concurrency:
  group: ${{ github.ref }}-${{ github.head_ref }}-macos
  cancel-in-progress: true

jobs:
  build_appleclang:
    name: AppleClang
    runs-on: macos-latest
    if: github.event.pull_request.draft == false
    env:
      CXXFLAGS: "-Werror -Wno-error=pass-failed"
      # For macOS, Ninja is slower than the default:
      #CMAKE_GENERATOR: Ninja
      SETUPTOOLS_USE_DISTUTILS: stdlib
    steps:
    - uses: actions/checkout@v3
    - name: install dependencies
      run: |
        brew
        set +e
        brew unlink gcc
        brew update
        brew install --overwrite python
        brew install fftw
        brew install libomp
        brew link --force libomp
        brew install ninja
        brew install open-mpi
        brew install pkg-config
        set -e
        brew tap openpmd/openpmd
        brew install openpmd-api
        python3 -m pip install matplotlib
        python3 -m pip install numpy
        python3 -m pip install scipy
    - name: build HiPACE++
      run: |
        cmake -S . -B build_sp          \
          -DCMAKE_VERBOSE_MAKEFILE=ON   \
          -DHiPACE_openpmd_internal=OFF \
          -DHiPACE_PRECISION=SINGLE
        cmake --build build_sp -j 2

#    - name: test HiPACE++
#      run: |
#        ctest --test-dir build_sp --output-on-failure
